In [9]:
import pandas as pd

df = pd.read_csv("../data/raw/listings.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,164448,Double room in central Stockholm with Wi-Fi,784312,Li,NaN,Södermalms,59.31389,18.06087,Private room,917.0,2,454,2025-09-23,2.63,2,169,27,NaN
1,220851,One room in appartement,412283,Fredric,NaN,Kungsholmens,59.33351,18.03693,Private room,450.0,2,66,2025-01-19,0.39,2,296,2,NaN
2,238411,Cozy apartment in central Stockholm,1250232,Mia,NaN,Norrmalms,59.33872,18.05131,Entire home/apt,1073.0,1,110,2016-12-13,0.65,1,79,0,NaN
3,242188,Single room in central Stockholm with Wi-Fi,784312,Li,NaN,Södermalms,59.31198,18.06076,Private room,779.0,2,444,2025-09-21,2.68,2,168,33,NaN
4,273906,Penthouse in central Stockholm,1432722,Rodrigo,NaN,Södermalms,59.30543,18.10771,Entire home/apt,2352.0,6,4,2017-07-31,0.02,2,271,0,NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4955 entries, 0 to 4954
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4955 non-null   int64
 1   name                            4955 non-null   str
 2   host_id                         4955 non-null   int64
 3   host_name                       4951 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   4955 non-null   str
 6   latitude                        4955 non-null   float64
 7   longitude                       4955 non-null   float64
 8   room_type                       4955 non-null   str
 9   price                           3190 non-null   float64
 10  minimum_nights                  4955 non-null   int64
 11  number_of_reviews               4955 non-null   int64
 12  last_review                     4086 non-null   str
 13  reviews_per_month               4086 non-null   float64
 14  calculated_host_listings_count  4955 non-null   int64
 15  availability_365                4955 non-null   int64
 16  number_of_reviews_ltm           4955 non-null   int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), str(5)
memory usage: 696.9 KB

In [11]:
df.isnull().sum()

id                                   0
name                                 0
host_id                              0
host_name                            4
neighbourhood_group               4955
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                             1765
minimum_nights                       0
number_of_reviews                    0
last_review                        869
reviews_per_month                  869
calculated_host_listings_count       0
availability_365                     0
number_of_reviews_ltm                0
license                           4955
dtype: int64

In [15]:
rows_before_cleaning=df.shape[0]
rows_before_cleaning
df = df.dropna(subset=["price"])
rows_after_cleaning = df.shape[0]
rows_after_cleaning


df.to_csv("../data/cleaned/cleaned_listings.csv", index=False)
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,164448,Double room in central Stockholm with Wi-Fi,784312,Li,NaN,Södermalms,59.313890,18.060870,Private room,917.0,2,454,2025-09-23,2.63,2,169,27,NaN
1,220851,One room in appartement,412283,Fredric,NaN,Kungsholmens,59.333510,18.036930,Private room,450.0,2,66,2025-01-19,0.39,2,296,2,NaN
2,238411,Cozy apartment in central Stockholm,1250232,Mia,NaN,Norrmalms,59.338720,18.051310,Entire home/apt,1073.0,1,110,2016-12-13,0.65,1,79,0,NaN
3,242188,Single room in central Stockholm with Wi-Fi,784312,Li,NaN,Södermalms,59.311980,18.060760,Private room,779.0,2,444,2025-09-21,2.68,2,168,33,NaN
4,273906,Penthouse in central Stockholm,1432722,Rodrigo,NaN,Södermalms,59.305430,18.107710,Entire home/apt,2352.0,6,4,2017-07-31,0.02,2,271,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4950,1518315388896689673,Ljus lägenhet med balkong - Abrahamsberg,526490748,Kevin,NaN,Bromma,59.337940,17.958160,Entire home/apt,567.0,3,0,NaN,NaN,3,33,0,NaN
4951,1518947120255495232,Furnished Room in the Heart of Stockholm,397878986,Unni,NaN,Södermalms,59.312391,18.095422,Private room,272.0,1,0,NaN,NaN,1,352,0,NaN
4952,1518992217482651420,Attefallshus,330762003,Niklas,NaN,Hässelby-Vällingby,59.377580,17.820526,Entire home/apt,657.0,1,0,NaN,NaN,1,355,0,NaN
4953,1519642719140641464,Worker & Family Studio • 2 Beds + Fully equipped,497702675,Wilhelm Gustav,NaN,Farsta,59.242870,18.117230,Entire home/apt,819.0,1,0,NaN,NaN,2,358,0,NaN
4954,1519716586978462297,Beautiful and cozy room with new floor & new b...,581635297,Elizabeth,NaN,Enskede-Årsta-Vantörs,59.262700,18.010190,Private room,417.0,1,0,NaN,NaN,1,364,0,NaN

## Average Airbnb price in Stockhom

In [17]:
df["price"].mean()

np.float64(1690.4730407523512)

## Price by room type

In [24]:
price_by_room_type=(
    df.groupby("room_type")["price"]
    .mean()
    .reset_index(name="average price")
)
price_by_room_type

         room_type  average price
0  Entire home/apt    1781.735433
1       Hotel room     303.000000
2     Private room    1374.236715
3      Shared room     474.892857

## Most expensive neighbourhoods

In [29]:
price_by_neighbourhood =(
    df.groupby("neighbourhood")["price"]
    .mean()
    .sort_values(ascending=False)
    .round(2)
    .reset_index()
)
price_by_neighbourhood

             neighbourhood    price
0                Norrmalms  2643.11
1                   Bromma  2302.66
2               Östermalms  2002.16
3               Södermalms  1761.61
4                   Älvsjö  1647.37
5             Kungsholmens  1542.04
6                   Farsta  1532.74
7   Hägersten-Liljeholmens  1470.28
8       Hässelby-Vällingby  1358.87
9    Enskede-Årsta-Vantörs  1345.03
10              Skarpnäcks  1227.06
11           Spånga-Tensta  1025.21
12          Rinkeby-Tensta   840.76
13             Skärholmens   826.64

## Listings Vs Reviews

In [ ]:
df[["price","number_of_reviews"]].corr()
## Check

                      price  number_of_reviews
price              1.000000          -0.039242
number_of_reviews -0.039242           1.000000